"""add credit sales tracking

Revision ID: 0a6752260382
Revises: dede5306f336
Create Date: 2025-12-09 23:31:21.275170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6752260382'
down_revision: Union[str, None] = 'dede5306f336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_sales_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
        batch_op.add_column(sa.Column('credit_payments_collected', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_column('credit_payments_collected')
        batch_op.drop_column('credit_sales_total')

    # ### end Alembic commands ###
