"""simplify_session_status_to_string

Revision ID: 1627e73675db
Revises: fba67649e018
Create Date: 2025-10-27 17:55:54.266647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1627e73675db'
down_revision: Union[str, None] = 'fba67649e018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))

    # ### end Alembic commands ###
