"""add movements table

Revision ID: 3b483782802e
Revises: 011704d3b342
Create Date: 2025-10-16 19:26:17.554892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b483782802e'
down_revision: Union[str, None] = '011704d3b342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='movement_type'), nullable=False),
    sa.Column('amount_gs', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_type'))
        batch_op.drop_index(batch_op.f('ix_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_movements_category'))

    op.drop_table('movements')
    # ### end Alembic commands ###
