"""add_business_cash_sessions_relationship

Revision ID: 5a4d88718d86
Revises: fa721efd4e80
Create Date: 2025-10-23 18:35:01.772096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4d88718d86'
down_revision: Union[str, None] = 'fa721efd4e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
