"""add_business_cash_sessions_relationship

Revision ID: 69c7967bad4c
Revises: 5a4d88718d86
Create Date: 2025-10-23 18:37:14.341072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c7967bad4c'
down_revision: Union[str, None] = '5a4d88718d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
