"""add_categories_table

Revision ID: 9f3c2a80132a
Revises: 3b483782802e
Create Date: 2025-10-20 16:17:29.412209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3c2a80132a'
down_revision: Union[str, None] = '3b483782802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'BOTH', name='category_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_type'), ['type'], unique=False)

    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.UUID(), nullable=True))
        batch_op.drop_index('ix_movements_category')
        batch_op.create_index(batch_op.f('ix_movements_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movements_category_id'))
        batch_op.create_index('ix_movements_category', ['category'], unique=False)
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_type'))
        batch_op.drop_index(batch_op.f('ix_categories_is_active'))

    op.drop_table('categories')
    # ### end Alembic commands ###
