"""split_opened_at_closed_at_to_date_time_columns

Revision ID: 9f6320c9ee99
Revises: 1eb24aa32aa5
Create Date: 2025-11-15 01:13:51.442392

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9f6320c9ee99'
down_revision: Union[str, None] = '1eb24aa32aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns as nullable first
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('opened_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('closed_time', sa.Time(), nullable=True))

    # Migrate data: extract date and time from existing datetime columns
    op.execute("""
        UPDATE cash_sessions
        SET 
            session_date = opened_at::date,
            opened_time = opened_at::time
        WHERE opened_at IS NOT NULL
    """)

    op.execute("""
        UPDATE cash_sessions
        SET closed_time = closed_at::time
        WHERE closed_at IS NOT NULL
    """)

    # Make session_date and opened_time NOT NULL (all rows now have values)
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('session_date', nullable=False)
        batch_op.alter_column('opened_time', nullable=False)
        # closed_time stays nullable (open sessions have no closed_at)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('opened_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # Reconstruct datetime from date + time
    op.execute("""
        UPDATE cash_sessions
        SET opened_at = session_date + opened_time
        WHERE session_date IS NOT NULL AND opened_time IS NOT NULL
    """)

    op.execute("""
        UPDATE cash_sessions
        SET closed_at = session_date + closed_time
        WHERE session_date IS NOT NULL AND closed_time IS NOT NULL
    """)

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_column('closed_time')
        batch_op.drop_column('opened_time')
        batch_op.drop_column('session_date')

    # ### end Alembic commands ###