"""add_daily_reconciliation_tables

Revision ID: cce21123ed07
Revises: a1b2c3d4e5f6
Create Date: 2026-01-05 12:48:48.504648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce21123ed07'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('card_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refunds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reconciliations_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reconciliations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reconciliations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reconciliations_is_closed'), ['is_closed'], unique=False)

    op.create_table('daily_reconciliation_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['daily_reconciliations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reconciliation_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reconciliation_audit_logs_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reconciliation_audit_logs_reconciliation_id'), ['reconciliation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reconciliation_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reconciliation_audit_logs_reconciliation_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reconciliation_audit_logs_changed_at'))

    op.drop_table('daily_reconciliation_audit_logs')
    with op.batch_alter_table('daily_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reconciliations_is_closed'))
        batch_op.drop_index(batch_op.f('ix_daily_reconciliations_date'))
        batch_op.drop_index(batch_op.f('ix_daily_reconciliations_business_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reconciliations_admin_id'))

    op.drop_table('daily_reconciliations')
    # ### end Alembic commands ###
