# File: alembic/versions/d31d1e1b81de_create_user_business_table.py
"""create_user_business_table

Revision ID: d31d1e1b81de
Revises: 85f44c4614fb
Create Date: 2025-11-29 18:05:47.602505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31d1e1b81de'
down_revision: Union[str, None] = '85f44c4614fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_businesses_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_businesses_user_id'), ['user_id'], unique=False)
        # ADD: Composite unique index for (user_id, business_id)
        batch_op.create_index('ix_user_businesses_user_business', ['user_id', 'business_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_businesses', schema=None) as batch_op:
        batch_op.drop_index('ix_user_businesses_user_business')  # ADD
        batch_op.drop_index(batch_op.f('ix_user_businesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_businesses_business_id'))

    op.drop_table('user_businesses')
    # ### end Alembic commands ###