"""add_payment_method_totals_remove_expected_sales

Revision ID: d3e16b91b0a8
Revises: 1627e73675db
Create Date: 2025-10-28 02:11:02.676684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e16b91b0a8'
down_revision: Union[str, None] = '1627e73675db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        # Add columns as nullable first
        batch_op.add_column(sa.Column('credit_card_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('debit_card_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bank_transfer_total', sa.Numeric(precision=12, scale=2), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE cash_sessions SET credit_card_total = 0.00 WHERE credit_card_total IS NULL")
    op.execute("UPDATE cash_sessions SET debit_card_total = 0.00 WHERE debit_card_total IS NULL")
    op.execute("UPDATE cash_sessions SET bank_transfer_total = 0.00 WHERE bank_transfer_total IS NULL")

    # Now make them NOT NULL
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('credit_card_total', nullable=False)
        batch_op.alter_column('debit_card_total', nullable=False)
        batch_op.alter_column('bank_transfer_total', nullable=False)
        batch_op.drop_column('expected_sales')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_sales', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('bank_transfer_total')
        batch_op.drop_column('debit_card_total')
        batch_op.drop_column('credit_card_total')

    # Set default for expected_sales if needed
    op.execute("UPDATE cash_sessions SET expected_sales = 0.00 WHERE expected_sales IS NULL")

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('expected_sales', nullable=False)

    # ### end Alembic commands ###