"""remove_shift_hours_add_validation

Revision ID: d84bc1f3a8f1
Revises: d3e16b91b0a8
Create Date: 2025-11-10 18:09:44.757810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84bc1f3a8f1'
down_revision: Union[str, None] = 'd3e16b91b0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_column('shift_hours')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_hours', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
