"""drop_cashiers_json_column

Revision ID: dede5306f336
Revises: 5714760ead58
Create Date: 2025-12-08 21:10:18.808274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dede5306f336'
down_revision: Union[str, None] = '5714760ead58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('cashiers')

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_sessions_business_cashier')
        batch_op.drop_column('cashier_name')

    with op.batch_alter_table('user_businesses', schema=None) as batch_op:
        batch_op.drop_index('ix_user_businesses_user_business')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_businesses', schema=None) as batch_op:
        batch_op.create_index('ix_user_businesses_user_business', ['user_id', 'business_id'], unique=True)

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier_name', sa.VARCHAR(), server_default=sa.text("'Unknown'::character varying"), autoincrement=False, nullable=False))
        batch_op.create_index('ix_cash_sessions_business_cashier', ['business_id', 'cashier_id'], unique=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashiers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
