"""add_cash_session_table

Revision ID: fa721efd4e80
Revises: 8a158621c80e
Create Date: 2025-10-23 16:41:26.272416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa721efd4e80'
down_revision: Union[str, None] = '8a158621c80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('initial_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('envelope_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_business_id'))

    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
