"""add_session_status_cashier_shift_fields

Revision ID: fba67649e018
Revises: 69c7967bad4c
Create Date: 2025-10-27 16:35:18.876974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba67649e018'
down_revision: Union[str, None] = '69c7967bad4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type manually for PostgreSQL
    op.execute("CREATE TYPE sessionstatus AS ENUM ('OPEN', 'CLOSED')")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='sessionstatus', native_enum=False), nullable=False,
                      server_default='OPEN'))
        batch_op.add_column(sa.Column('cashier_name', sa.String(), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('shift_hours', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closing_ticket', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cash_sessions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_status'))
        batch_op.drop_column('notes')
        batch_op.drop_column('closing_ticket')
        batch_op.drop_column('shift_hours')
        batch_op.drop_column('cashier_name')
        batch_op.drop_column('status')

    # Drop enum type
    op.execute("DROP TYPE IF EXISTS sessionstatus")

    # ### end Alembic commands ###
